modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL="https://github.com/iStillStealSteel/RusticOrigins/issues"

[[mods]]
modId = "origins_rustic"
version = "${version}"
displayName = "Origins: Rustic"
displayURL="https://github.com/iStillStealSteel/RusticOrigins"
logoFile="pack.png"
credits="Thanks Apace for the original work, thanks EdwinMindcraft for the forge port, and thanks to limonblaze for this architecture!"
authors="iStillStealSteel (Bobo)"
description = "An add-on for the Origins mod which adds classes to the game for Rustic-Craft server."

[[dependencies.origins_rustic]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_requirements}"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins_rustic]]
modId = "forge"
mandatory = true
versionRange = "${forge_requirements}"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins_rustic]]
modId = "origins"
mandatory = true
versionRange = "${origins_requirements}"
ordering = "NONE"
side = "BOTH"
