@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.istillstealsteel.originsrustic.common.apoli.power;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;