@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.istillstealsteel.originsrustic.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;